    - name: Run SSH4Me Action
        uses: Jisan09/SSH4Me@main
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          PASSWORD: ${{ secrets.PASSWORD }}
          
      cache-from: type=gha
          cache-to: type=gha,mode=max

          cache-from: type=gha
          cache-to: type=gha,mode=max
  
